schema-version: 1.0


const:
  mysqlHome: /usr/local/mysql

var:
  version: 10.5.8
  rootpassword: password
  data: /var/lib/mysql
  port: "3306"
  log: /var/log/mariadb

ports:
  - "{% port %}"

persistent-dirs:
  - name: data
    intern: "{% data %}"
  - name: log
    intern: "{% log %}"

provision:
  - user:
      name: mysql
      group: mysql
  - url:
      from: https://downloads.mariadb.com/MariaDB/mariadb-{% version %}/bintar-linux-systemd-x86_64/mariadb-{% version %}-linux-systemd-x86_64.tar.gz
      to: /usr/local
      after: ln -s /usr/local/mariadb-{% version %}-linux-systemd-x86_64 {% mysqlHome %}
  - systempath: "{% mysqlHome %}/bin"
  - folder: /etc/my.cnf.d
  - copy:
      template: my.cnf
      todir: /etc
      after: cd {% mysqlHome %} && ./scripts/mysql_install_db --user=mysql
  - permission:
      path: /usr/local/mariadb-{% version %}-linux-systemd-x86_64
      owner: root
      group: root
      recursive: true
  - permission:
      path: "{% data %}"
      owner: mysql
      group: mysql
      recursive: true
  - shell: "{% mysqlHome %}/support-files/mysql.server start"
  - shell: "{{ .templates }}/secure.sh"
  - shell: "{% mysqlHome %}/support-files/mysql.server stop"

up: start
down: stop

command:
  start: "{% mysqlHome %}/support-files/mysql.server start"
  stop:
    container:
      create: false
    cmd: "{% mysqlHome %}/support-files/mysql.server stop"
