schema-version: 1.0
name: mariadb

var:
  rootpassword: password

ports:
  - "3306"

provision:
  - pkg: mariadb-server mariadb
  - shell: systemctl start mariadb
  - shell: secure.sh

up: start
down: stop

command:
  start: systemctl start mariadb
  stop:
    container:
      create: false
    inline: systemctl stop mariadb
